#!/bin/sh -l
### BEGIN INIT INFO
# Provides: ldp-kafka-f
# Required-Start: $ldp-zookeeper-f
# Required-Stop: $ldp-flume-f
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: ldp kafka filter
### END INIT INFO

SERVICE_NAME=ldp-kafka-f
PID_PATH_NAME=/tmp/ldp-kafka-f-pid

export "LOG_DIR=$LDP_HOME/logs/ldp-kafka-f"
export KAFKA_HEAP_OPTS="$LDP_KAFKA_JVM_OPTS"

case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PID_PATH_NAME ]; then
            nohup $LDP_KAFKA_HOME/bin/kafka-server-start.sh $LDP_HOME/conf/ldp-kafka/ldp-kafka-f.properties 2>> /dev/null >> /dev/null & echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stopping ...";
            kill $PID;
            echo "$SERVICE_NAME stopped ...";
            rm $PID_PATH_NAME
            echo "$SERVICE_NAME starting ..."
            nohup $LDP_KAFKA_HOME/bin/kafka-server-start.sh $LDP_HOME/conf/ldp-kafka/ldp-kafka-f.properties 2>> /dev/null >> /dev/null & echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
esac 
